name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Run lint, type checks and tests
        run: yarn verify

      - name: Run build
        run: yarn turbo build --color --concurrency=5

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist

  # pre_release:
  #   runs-on: ubuntu-latest

  #   needs: build

  #   if: ${{ github.event_name == 'push' }}

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "16.15"
  #         registry-url: "https://registry.npmjs.org"

  #     - name: Cache dependencies
  #       id: cache
  #       uses: actions/cache@v3
  #       with:
  #         path: '**/node_modules'
  #         key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

  #     - name: Install dependencies
  #       if: steps.cache.outputs.cache-hit != 'true'
  #       run: yarn install --immutable
      
  #     - name: Version
  #       run: yarn lerna version "$(node -e "console.log(require('semver').inc(require('./lerna.json').version, 'patch'))")-pre.${{ github.run_number }}" --no-git-tag-version --no-push --yes
      
  #     - name: Build
  #       run: yarn turbo run build --color --concurrency=5
      
  #     - run: git config user.email "info@openmrs.org" && git config user.name "OpenMRS CI"
  #     - run: git add . && git commit -m "Prerelease version" --no-verify
      
  #     - name: Pre-release
  #       run: yarn run ci:prepublish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        
  #     - name: Upload Artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: packages
  #         path: |
  #           packages/**/dist
  
  # deploy_patient_management:
  #   runs-on: ubuntu-latest

  #   needs: pre_release

  #   if: ${{ github.event_name == 'push' }}

  #   steps:
  #     - name: Trigger RefApp Build
  #       uses: fjogeleit/http-request-action@master
  #       with:
  #         url: https://ci.openmrs.org/rest/api/latest/queue/REFAPP-D3X
  #         method: "POST"
  #         customHeaders: '{ "Authorization": "Bearer ${{ secrets.BAMBOO_TOKEN }}" }'

  # release:
  #   runs-on: ubuntu-latest

  #   needs: build

  #   if: ${{ github.event_name == 'release' }}

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Setup Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "16.15"
  #         registry-url: "https://registry.npmjs.org"

  #     - name: Cache dependencies
  #       id: cache
  #       uses: actions/cache@v3
  #       with:
  #         path: '**/node_modules'
  #         key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

  #     - name: Install dependencies
  #       if: steps.cache.outputs.cache-hit != 'true'
  #       run: yarn install --immutable

  #     - run: yarn turbo run build --color
  #     - run: yarn run ci:publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
